language: go

os:
  - linux

go:
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - 1.11
  - 1.12
  - 1.13

install:
  - make setup

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
